### ISSUE TITLE
地面点被识别为非地面点问题

### ISSUE THREAD

**Issue by WangY69** [EEPT-LAB/DipG-Seg#10]
感谢您的工作！

我想问下类似于被遮挡区域的点云边缘处，都被识别成了非地面点，这是为什么；

![pic1](https://github.com/EEPT-LAB/DipG-Seg/assets/53323745/879724e2-f469-45fa-aac9-a214e30f234b)
![pic2](https://github.com/EEPT-LAB/DipG-Seg/assets/53323745/494d46f6-6eca-4884-902c-ac484b0cfad1)

还有个问题：该算法似乎对于几个雷达拼接到一起的点云去地面效果差些？

**Comment by wenhao12111** [comment]
> 感谢您的工作！
> 
> 我想问下类似于被遮挡区域的点云边缘处，都被识别成了非地面点，这是为什么；
> 
> ![pic1](https://github.com/EEPT-LAB/DipG-Seg/assets/53323745/879724e2-f469-45fa-aac9-a214e30f234b)
> ![pic2](https://github.com/EEPT-LAB/DipG-Seg/assets/53323745/494d46f6-6eca-4884-902c-ac484b0cfad1)
> 
> 还有个问题：该算法似乎对于几个雷达拼接到一起的点云去地面效果差些？

第一个问题可以尝试通过改变image的分辨率得到一定的改善，我们的下一个版本中将会解决这个问题并进一步降低分割时间。
对于第二个问题，目前该方法只考虑单激光雷达的情况，详情可以参考我们的论文。（链接：https://www.researchgate.net/publication/376511620_DipG-Seg_Fast_and_Accurate_Double_Image-Based_Pixel-Wise_Ground_Segmentation）
