### ISSUE TITLE
耗时严重

### ISSUE THREAD

**Issue by shanyuejun** [EEPT-LAB/DipG-Seg#11]
在jetson orin 上原始点云数量50000左右，耗时60ms

**Comment by wenhao12111** [comment]
> 在jetson orin 上原始点云数量50000左右，耗时60ms

可以从以下几个方面验证该方法效率：
1. 确保您的平台的performance状态，cpu频率等是否和论文所展示的相近。
2. 确保在代码中加入std::cout进行信息打印或者插入其他耗时严重的代码段。
3. 确保projection_param中的参数与您的lidar参数对应。
