### ISSUE TITLE
About Adaptation to Solid-state LiDAR

### ISSUE THREAD

**Issue by qiaozhijian** [EEPT-LAB/DipG-Seg#2]
Hi, thanks for your nice work! 

Could you give some comments on the potential of the adaptation to solid-state LiDAR? Will it still work?

**Comment by wenhao12111** [comment]
Thanks for the issue. In fact, we are exactly submitting such a new work bringing considerable update. In terms of the current work, as long as you can project your lidar data to an image-based representation, you can get a decent result in theory, but the resolution may affect the result. By the way, the code has passed the final review, and we are going to release it in a few days.

**Comment by wenhao12111** [comment]
> Hi, thanks for your nice work!
> 
> Could you give some comments on the potential of the adaptation to solid-state LiDAR? Will it still work?

Thanks for the issue. In fact, we are exactly submitting such a new work bringing considerable update. In terms of the current work, as long as you can project your lidar data to an image-based representation, you can get a decent result in theory, but the resolution may affect the result. By the way, the code has passed the final review, and we are going to release it in a few days.

**Comment by qiaozhijian** [comment]
Congratulations! Hope to see it soon.
