### ISSUE TITLE
about paper

### ISSUE THREAD

**Issue by Nothand0212** [EEPT-LAB/DipG-Seg#5]
Hi~, Im not a ieee member. could you upload a pdf? thanks!!!!

**Comment by wenhao12111** [comment]
> Hi~, Im not a ieee member. could you upload a pdf? thanks!!!!

Dear Nothand0212,

We uploaded a preprint [here](https://www.researchgate.net/publication/376511620_DipG-Seg_Fast_and_Accurate_Double_Image-Based_Pixel-Wise_Ground_Segmentation) for your convenience. Please use it for a non-profit activity. Good luck!

**Comment by wenhao12111** [comment]
> Hi~, Im not a ieee member. could you upload a pdf? thanks!!!!

Can you see the paper now? If no further reply in this issue, I will close it.

**Comment by Nothand0212** [comment]
> > Hi~, Im not a ieee member. could you upload a pdf? thanks!!!!
> 
> Can you see the paper now? If no further reply in this issue, I will close it.

yeap, I had download it, thanks a lot~~~~

**Comment by wenhao12111** [comment]
> > > Hi~, Im not a ieee member. could you upload a pdf? thanks!!!!
> > 
> > Can you see the paper now? If no further reply in this issue, I will close it.
> 
> yeap, I had download it, thanks a lot~~~~

Ok~~~
