### ISSUE TITLE
Is it able to run with the robosense lidar(Helios 16)?

### ISSUE THREAD

**Issue by Sanford-zsh** [EEPT-LAB/DipG-Seg#6]
Hi~  It was mentioned in the paper that you tested the code with a 16-wire lidar and got good results. I want to use a robosense lidar to run the code. It is also a 16-beam lidar (Helios 16). I have modified some parameters. And I do not know how to modify the compensating vector(const static int cpst[16]). Could you tell me how to modify this parameter? Thanks a lot!

**Comment by wenhao12111** [comment]
> Hi~  It was mentioned in the paper that you tested the code with a 16-wire lidar and got good results. I want to use a robosense lidar to run the code. It is also a 16-beam lidar (Helios 16). I have modified some parameters. And I do not know how to modify the compensating vector(const static int cpst[16]). Could you tell me how to modify this parameter? Thanks a lot!

May I know your sensor height?

**Comment by Sanford-zsh** [comment]
> May I know your sensor height?
It is mounted on the robot and has a height of 0.6 meters

**Comment by Sanford-zsh** [comment]
> > Hi~  It was mentioned in the paper that you tested the code with a 16-wire lidar and got good results. I want to use a robosense lidar to run the code. It is also a 16-beam lidar (Helios 16). I have modified some parameters. And I do not know how to modify the compensating vector(const static int cpst[16]). Could you tell me how to modify this parameter? Thanks a lot!
> 
> May I know your sensor height?

It is mounted on the robot and has a height of 0.6 meters

**Comment by wenhao12111** [comment]
> > > Hi~  It was mentioned in the paper that you tested the code with a 16-wire lidar and got good results. I want to use a robosense lidar to run the code. It is also a 16-beam lidar (Helios 16). I have modified some parameters. And I do not know how to modify the compensating vector(const static int cpst[16]). Could you tell me how to modify this parameter? Thanks a lot!
> > 
> > May I know your sensor height?
> 
> It is mounted on the robot and has a height of 0.6 meters

With a rough calculation, you can have a try with a cpst[16] filled with 1, because the vertical resolution is too large to need compensation (under compensating distance is 0.3).

**Comment by Sanford-zsh** [comment]
I have tried to do what you said. But segmentation doesn't work very well. I have modified some parameters as follows:
![image](https://github.com/EEPT-LAB/DipG-Seg/assets/56405167/f9c7c6d9-0955-44fe-80a7-62a270a623a1)
In fact, my liDAR rear view is obscured by robotic parts. I don't know if that's going to make a difference to the segmentation result.


> > > > Hi~  It was mentioned in the paper that you tested the code with a 16-wire lidar and got good results. I want to use a robosense lidar to run the code. It is also a 16-beam lidar (Helios 16). I have modified some parameters. And I do not know how to modify the compensating vector(const static int cpst[16]). Could you tell me how to modify this parameter? Thanks a lot!
> > > 
> > > 
> > > May I know your sensor height?
> > 
> > 
> > It is mounted on the robot and has a height of 0.6 meters
> 
> With a rough calculation, you can have a try with a cpst[16] filled with 1, because the vertical resolution is too large to need compensation (under compensating distance is 0.3).

**Comment by wenhao12111** [comment]
> I have tried to do what you said. But segmentation doesn't work very well. I have modified some parameters as follows: ![image](https://private-user-images.githubusercontent.com/56405167/317651237-f9c7c6d9-0955-44fe-80a7-62a270a623a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTUzOTgsIm5iZiI6MTcxMTYxNTA5OCwicGF0aCI6Ii81NjQwNTE2Ny8zMTc2NTEyMzctZjljN2M2ZDktMDk1NS00NGZlLTgwYTctNjJhMjcwYTYyM2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA4MzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZjVkMTUyZGNjNWQ2ZmVjZmQ5ZjFhNWE3ZTg4OWJkMDk3Y2IwMDMwOTU4ZDlkZGEyYmQxYTRhNmVmZDE4OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19BcoCl4nNeTdmx_UC-PZBCQ5xv2z9w-Ms7uCxQodxI) In fact, my liDAR rear view is obscured by robotic parts. I don't know if that's going to make a difference to the segmentation result.
> 
> > > > > Hi~  It was mentioned in the paper that you tested the code with a 16-wire lidar and got good results. I want to use a robosense lidar to run the code. It is also a 16-beam lidar (Helios 16). I have modified some parameters. And I do not know how to modify the compensating vector(const static int cpst[16]). Could you tell me how to modify this parameter? Thanks a lot!
> > > > 
> > > > 
> > > > May I know your sensor height?
> > > 
> > > 
> > > It is mounted on the robot and has a height of 0.6 meters
> > 
> > 
> > With a rough calculation, you can have a try with a cpst[16] filled with 1, because the vertical resolution is too large to need compensation (under compensating distance is 0.3).

The situation you said is a potential problem for degrading the result. You can try to crop the part of the projected image within the valid angle range. This may work. If not, you can offer a segmentation result (image and pointcloud) to me for further discussion.

**Comment by Sanford-zsh** [comment]
> > I have tried to do what you said. But segmentation doesn't work very well. I have modified some parameters as follows: ![image](https://private-user-images.githubusercontent.com/56405167/317651237-f9c7c6d9-0955-44fe-80a7-62a270a623a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTUzOTgsIm5iZiI6MTcxMTYxNTA5OCwicGF0aCI6Ii81NjQwNTE2Ny8zMTc2NTEyMzctZjljN2M2ZDktMDk1NS00NGZlLTgwYTctNjJhMjcwYTYyM2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA4MzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZjVkMTUyZGNjNWQ2ZmVjZmQ5ZjFhNWE3ZTg4OWJkMDk3Y2IwMDMwOTU4ZDlkZGEyYmQxYTRhNmVmZDE4OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19BcoCl4nNeTdmx_UC-PZBCQ5xv2z9w-Ms7uCxQodxI) In fact, my liDAR rear view is obscured by robotic parts. I don't know if that's going to make a difference to the segmentation result.
> > > > > > Hi~  It was mentioned in the paper that you tested the code with a 16-wire lidar and got good results. I want to use a robosense lidar to run the code. It is also a 16-beam lidar (Helios 16). I have modified some parameters. And I do not know how to modify the compensating vector(const static int cpst[16]). Could you tell me how to modify this parameter? Thanks a lot!
> > > > > 
> > > > > 
> > > > > May I know your sensor height?
> > > > 
> > > > 
> > > > It is mounted on the robot and has a height of 0.6 meters
> > > 
> > > 
> > > With a rough calculation, you can have a try with a cpst[16] filled with 1, because the vertical resolution is too large to need compensation (under compensating distance is 0.3).
> 
> The situation you said is a potential problem for degrading the result. You can try to crop the part of the projected image within the valid angle range. This may work. If not, you can offer a segmentation result (image and pointcloud) to me for further discussion.

I have tried  to crop the part of the projected image within the valid angle range. However, it still does not work very well. I can offer a bag file to you. How can I send the bag file to you?

**Comment by wenhao12111** [comment]
> > > I have tried to do what you said. But segmentation doesn't work very well. I have modified some parameters as follows: ![image](https://private-user-images.githubusercontent.com/56405167/317651237-f9c7c6d9-0955-44fe-80a7-62a270a623a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTUzOTgsIm5iZiI6MTcxMTYxNTA5OCwicGF0aCI6Ii81NjQwNTE2Ny8zMTc2NTEyMzctZjljN2M2ZDktMDk1NS00NGZlLTgwYTctNjJhMjcwYTYyM2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA4MzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZjVkMTUyZGNjNWQ2ZmVjZmQ5ZjFhNWE3ZTg4OWJkMDk3Y2IwMDMwOTU4ZDlkZGEyYmQxYTRhNmVmZDE4OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19BcoCl4nNeTdmx_UC-PZBCQ5xv2z9w-Ms7uCxQodxI) In fact, my liDAR rear view is obscured by robotic parts. I don't know if that's going to make a difference to the segmentation result.
> > > > > > > Hi~  It was mentioned in the paper that you tested the code with a 16-wire lidar and got good results. I want to use a robosense lidar to run the code. It is also a 16-beam lidar (Helios 16). I have modified some parameters. And I do not know how to modify the compensating vector(const static int cpst[16]). Could you tell me how to modify this parameter? Thanks a lot!
> > > > > > 
> > > > > > 
> > > > > > May I know your sensor height?
> > > > > 
> > > > > 
> > > > > It is mounted on the robot and has a height of 0.6 meters
> > > > 
> > > > 
> > > > With a rough calculation, you can have a try with a cpst[16] filled with 1, because the vertical resolution is too large to need compensation (under compensating distance is 0.3).
> > 
> > The situation you said is a potential problem for degrading the result. You can try to crop the part of the projected image within the valid angle range. This may work. If not, you can offer a segmentation result (image and pointcloud) to me for further discussion.
> 
> I have tried  to crop the part of the projected image within the valid angle range. However, it still does not work very well. I can offer a bag file to you. How can I send the bag file to you?

You can show me the visualized result first so that I can analyze fast.

**Comment by Sanford-zsh** [comment]
OK. I made a video, and it shows the result of segmentation.
https://github.com/EEPT-LAB/DipG-Seg/assets/56405167/cc850a23-d89a-4e42-b53a-13f109ecb45d



> > > > I have tried to do what you said. But segmentation doesn't work very well. I have modified some parameters as follows: ![image](https://private-user-images.githubusercontent.com/56405167/317651237-f9c7c6d9-0955-44fe-80a7-62a270a623a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTUzOTgsIm5iZiI6MTcxMTYxNTA5OCwicGF0aCI6Ii81NjQwNTE2Ny8zMTc2NTEyMzctZjljN2M2ZDktMDk1NS00NGZlLTgwYTctNjJhMjcwYTYyM2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA4MzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZjVkMTUyZGNjNWQ2ZmVjZmQ5ZjFhNWE3ZTg4OWJkMDk3Y2IwMDMwOTU4ZDlkZGEyYmQxYTRhNmVmZDE4OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19BcoCl4nNeTdmx_UC-PZBCQ5xv2z9w-Ms7uCxQodxI) In fact, my liDAR rear view is obscured by robotic parts. I don't know if that's going to make a difference to the segmentation result.
> > > > > > > > Hi~  It was mentioned in the paper that you tested the code with a 16-wire lidar and got good results. I want to use a robosense lidar to run the code. It is also a 16-beam lidar (Helios 16). I have modified some parameters. And I do not know how to modify the compensating vector(const static int cpst[16]). Could you tell me how to modify this parameter? Thanks a lot!
> > > > > > > 
> > > > > > > 
> > > > > > > May I know your sensor height?
> > > > > > 
> > > > > > 
> > > > > > It is mounted on the robot and has a height of 0.6 meters
> > > > > 
> > > > > 
> > > > > With a rough calculation, you can have a try with a cpst[16] filled with 1, because the vertical resolution is too large to need compensation (under compensating distance is 0.3).
> > > 
> > > 
> > > The situation you said is a potential problem for degrading the result. You can try to crop the part of the projected image within the valid angle range. This may work. If not, you can offer a segmentation result (image and pointcloud) to me for further discussion.
> > 
> > 
> > I have tried  to crop the part of the projected image within the valid angle range. However, it still does not work very well. I can offer a bag file to you. How can I send the bag file to you?
> 
> You can show me the visualized result first so that I can analyze fast.

**Comment by wenhao12111** [comment]
> OK. I made a video, and it shows the result of segmentation. https://github.com/EEPT-LAB/DipG-Seg/assets/56405167/cc850a23-d89a-4e42-b53a-13f109ecb45d
> 
> > > > > I have tried to do what you said. But segmentation doesn't work very well. I have modified some parameters as follows: ![image](https://private-user-images.githubusercontent.com/56405167/317651237-f9c7c6d9-0955-44fe-80a7-62a270a623a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTUzOTgsIm5iZiI6MTcxMTYxNTA5OCwicGF0aCI6Ii81NjQwNTE2Ny8zMTc2NTEyMzctZjljN2M2ZDktMDk1NS00NGZlLTgwYTctNjJhMjcwYTYyM2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA4MzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZjVkMTUyZGNjNWQ2ZmVjZmQ5ZjFhNWE3ZTg4OWJkMDk3Y2IwMDMwOTU4ZDlkZGEyYmQxYTRhNmVmZDE4OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19BcoCl4nNeTdmx_UC-PZBCQ5xv2z9w-Ms7uCxQodxI) In fact, my liDAR rear view is obscured by robotic parts. I don't know if that's going to make a difference to the segmentation result.
> > > > > > > > > Hi~  It was mentioned in the paper that you tested the code with a 16-wire lidar and got good results. I want to use a robosense lidar to run the code. It is also a 16-beam lidar (Helios 16). I have modified some parameters. And I do not know how to modify the compensating vector(const static int cpst[16]). Could you tell me how to modify this parameter? Thanks a lot!
> > > > > > > > 
> > > > > > > > 
> > > > > > > > May I know your sensor height?
> > > > > > > 
> > > > > > > 
> > > > > > > It is mounted on the robot and has a height of 0.6 meters
> > > > > > 
> > > > > > 
> > > > > > With a rough calculation, you can have a try with a cpst[16] filled with 1, because the vertical resolution is too large to need compensation (under compensating distance is 0.3).
> > > > 
> > > > 
> > > > The situation you said is a potential problem for degrading the result. You can try to crop the part of the projected image within the valid angle range. This may work. If not, you can offer a segmentation result (image and pointcloud) to me for further discussion.
> > > 
> > > 
> > > I have tried  to crop the part of the projected image within the valid angle range. However, it still does not work very well. I can offer a bag file to you. How can I send the bag file to you?
> > 
> > 
> > You can show me the visualized result first so that I can analyze fast.

Ok, I have seen your video. First, you can try to fix a potential bug [here](https://github.com/EEPT-LAB/DipG-Seg/blob/182e34843082295c79b59d7643a1f13c0f910919/src/include/dipgseg.h#L527C13-L527C75). You can replace this line with:

```c++
if(repaired_img_d.at<float>(r-j,c) - repaired_img_d.at<float>(r,c)<0){
    d_vertical.at<float>(r-1,c) = 0.00001; // to guarantee the slope in this pixel is very large
}
else{
    d_vertical.at<float>(r-1,c) = repaired_img_d.at<float>(r-j,c) - repaired_img_d.at<float>(r,c)+0.001;
}
```

Besides, you can use 'cv::imshow()' to see your image's quality (high quality means less empty hole). If the quality is poor, this will affect the final result. If poor quality, you can try to transform your point cloud into a smoother image (As known by us, someone who used our method has tried this way to get a better segmentation result).

Finally, if the above ways cannot help you, you can try to adjust the thresholds mentioned in the paper with the guidance of the parameter study and analysis.

Hope the above ways can help.

**Comment by Sanford-zsh** [comment]
> ```c++
> 0.00001
> ```

I had modified the code as you said. And it worked better than before obviously. I think there are still some parameters that need to be fine-tuned to make it better. Thank you so much!
https://github.com/EEPT-LAB/DipG-Seg/assets/56405167/149e1c58-4291-46bb-8cac-a18c3b7a3abc

**Comment by Sanford-zsh** [comment]
> > OK. I made a video, and it shows the result of segmentation. https://github.com/EEPT-LAB/DipG-Seg/assets/56405167/cc850a23-d89a-4e42-b53a-13f109ecb45d
> > > > > > I have tried to do what you said. But segmentation doesn't work very well. I have modified some parameters as follows: ![image](https://private-user-images.githubusercontent.com/56405167/317651237-f9c7c6d9-0955-44fe-80a7-62a270a623a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTUzOTgsIm5iZiI6MTcxMTYxNTA5OCwicGF0aCI6Ii81NjQwNTE2Ny8zMTc2NTEyMzctZjljN2M2ZDktMDk1NS00NGZlLTgwYTctNjJhMjcwYTYyM2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA4MzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZjVkMTUyZGNjNWQ2ZmVjZmQ5ZjFhNWE3ZTg4OWJkMDk3Y2IwMDMwOTU4ZDlkZGEyYmQxYTRhNmVmZDE4OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19BcoCl4nNeTdmx_UC-PZBCQ5xv2z9w-Ms7uCxQodxI) In fact, my liDAR rear view is obscured by robotic parts. I don't know if that's going to make a difference to the segmentation result.
> > > > > > > > > > Hi~  It was mentioned in the paper that you tested the code with a 16-wire lidar and got good results. I want to use a robosense lidar to run the code. It is also a 16-beam lidar (Helios 16). I have modified some parameters. And I do not know how to modify the compensating vector(const static int cpst[16]). Could you tell me how to modify this parameter? Thanks a lot!
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > May I know your sensor height?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It is mounted on the robot and has a height of 0.6 meters
> > > > > > > 
> > > > > > > 
> > > > > > > With a rough calculation, you can have a try with a cpst[16] filled with 1, because the vertical resolution is too large to need compensation (under compensating distance is 0.3).
> > > > > 
> > > > > 
> > > > > The situation you said is a potential problem for degrading the result. You can try to crop the part of the projected image within the valid angle range. This may work. If not, you can offer a segmentation result (image and pointcloud) to me for further discussion.
> > > > 
> > > > 
> > > > I have tried  to crop the part of the projected image within the valid angle range. However, it still does not work very well. I can offer a bag file to you. How can I send the bag file to you?
> > > 
> > > 
> > > You can show me the visualized result first so that I can analyze fast.
> 
> Ok, I have seen your video. First, you can try to fix a potential bug [here](https://github.com/EEPT-LAB/DipG-Seg/blob/182e34843082295c79b59d7643a1f13c0f910919/src/include/dipgseg.h#L527C13-L527C75). You can replace this line with:
> 
> ```c++
> if(repaired_img_d.at<float>(r-j,c) - repaired_img_d.at<float>(r,c)<0){
>     d_vertical.at<float>(r-1,c) = 0.00001; // to guarantee the slope in this pixel is very large
> }
> else{
>     d_vertical.at<float>(r-1,c) = repaired_img_d.at<float>(r-j,c) - repaired_img_d.at<float>(r,c)+0.001;
> }
> ```
> 
> Besides, you can use 'cv::imshow()' to see your image's quality (high quality means less empty hole). If the quality is poor, this will affect the final result. If poor quality, you can try to transform your point cloud into a smoother image (As known by us, someone who used our method has tried this way to get a better segmentation result).
> 
> Finally, if the above ways cannot help you, you can try to adjust the thresholds mentioned in the paper with the guidance of the parameter study and analysis.
> 
> Hope the above ways can help.

I had modified the code as you said. And it worked better than before obviously. I think there are still some parameters that need to be fine-tuned to make it better. Thank you so much!

https://github.com/EEPT-LAB/DipG-Seg/assets/56405167/c9211fd9-b182-472a-9aca-fc2d2ed73463

**Comment by wenhao12111** [comment]
> > > OK. I made a video, and it shows the result of segmentation. https://github.com/EEPT-LAB/DipG-Seg/assets/56405167/cc850a23-d89a-4e42-b53a-13f109ecb45d
> > > > > > > I have tried to do what you said. But segmentation doesn't work very well. I have modified some parameters as follows: ![image](https://private-user-images.githubusercontent.com/56405167/317651237-f9c7c6d9-0955-44fe-80a7-62a270a623a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTUzOTgsIm5iZiI6MTcxMTYxNTA5OCwicGF0aCI6Ii81NjQwNTE2Ny8zMTc2NTEyMzctZjljN2M2ZDktMDk1NS00NGZlLTgwYTctNjJhMjcwYTYyM2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA4MzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZjVkMTUyZGNjNWQ2ZmVjZmQ5ZjFhNWE3ZTg4OWJkMDk3Y2IwMDMwOTU4ZDlkZGEyYmQxYTRhNmVmZDE4OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.19BcoCl4nNeTdmx_UC-PZBCQ5xv2z9w-Ms7uCxQodxI) In fact, my liDAR rear view is obscured by robotic parts. I don't know if that's going to make a difference to the segmentation result.
> > > > > > > > > > > Hi~  It was mentioned in the paper that you tested the code with a 16-wire lidar and got good results. I want to use a robosense lidar to run the code. It is also a 16-beam lidar (Helios 16). I have modified some parameters. And I do not know how to modify the compensating vector(const static int cpst[16]). Could you tell me how to modify this parameter? Thanks a lot!
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > May I know your sensor height?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > It is mounted on the robot and has a height of 0.6 meters
> > > > > > > > 
> > > > > > > > 
> > > > > > > > With a rough calculation, you can have a try with a cpst[16] filled with 1, because the vertical resolution is too large to need compensation (under compensating distance is 0.3).
> > > > > > 
> > > > > > 
> > > > > > The situation you said is a potential problem for degrading the result. You can try to crop the part of the projected image within the valid angle range. This may work. If not, you can offer a segmentation result (image and pointcloud) to me for further discussion.
> > > > > 
> > > > > 
> > > > > I have tried  to crop the part of the projected image within the valid angle range. However, it still does not work very well. I can offer a bag file to you. How can I send the bag file to you?
> > > > 
> > > > 
> > > > You can show me the visualized result first so that I can analyze fast.
> > 
> > 
> > Ok, I have seen your video. First, you can try to fix a potential bug [here](https://github.com/EEPT-LAB/DipG-Seg/blob/182e34843082295c79b59d7643a1f13c0f910919/src/include/dipgseg.h#L527C13-L527C75). You can replace this line with:
> > ```c++
> > if(repaired_img_d.at<float>(r-j,c) - repaired_img_d.at<float>(r,c)<0){
> >     d_vertical.at<float>(r-1,c) = 0.00001; // to guarantee the slope in this pixel is very large
> > }
> > else{
> >     d_vertical.at<float>(r-1,c) = repaired_img_d.at<float>(r-j,c) - repaired_img_d.at<float>(r,c)+0.001;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Besides, you can use 'cv::imshow()' to see your image's quality (high quality means less empty hole). If the quality is poor, this will affect the final result. If poor quality, you can try to transform your point cloud into a smoother image (As known by us, someone who used our method has tried this way to get a better segmentation result).
> > Finally, if the above ways cannot help you, you can try to adjust the thresholds mentioned in the paper with the guidance of the parameter study and analysis.
> > Hope the above ways can help.
> 
> I had modified the code as you said. And it worked better than before obviously. I think there are still some parameters that need to be fine-tuned to make it better. Thank you so much!
> 
>  seg_ground1.mp4

So glad the suggestions can help you. Good luck!
