### ISSUE TITLE
roslaunch dipgseg visualization_offline_kitti.launch  error

### ISSUE THREAD

**Issue by Anmidy** [EEPT-LAB/DipG-Seg#7]
hello, when i run the visualization_offline_kitti.launch, there is en error of length, the log is such as the follow, an the rviz is nothing visualize.

`(base) kilox@xsq:~/code/code/detect/offline_function/video_detect_function/catkin_ws$ roslaunch dipgseg visualization_offline_kitti.launch 
... logging to /home/kilox/.ros/log/f875ab82-eda8-11ee-b1e3-244bfe056dd7/roslaunch-xsq-28590.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://xsq:42355/

SUMMARY
========

PARAMETERS
 * /dataset_path: /home/kilox/code/...
 * /eval_flag: False
 * /output_path: /home/kilox/code/...
 * /rosdistro: melodic
 * /rosversion: 1.14.13
 * /verbose: True

NODES
  /
    dipgseg_node (dipgseg/offline_kitti_node)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [28604]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to f875ab82-eda8-11ee-b1e3-244bfe056dd7
process[rosout-1]: started with pid [28617]
started core service [/rosout]
process[rviz-2]: started with pid [28626]
process[dipgseg_node-3]: started with pid [28634]
now time is----------*********: 2024-03-29-16-47-28
INFO: Getting file paths from folder: /home/kilox/code/dataset_4090/SemanticKITTI/ScribbleKITTI/data_odometry_voxels_all/sequences/10/voxels
INFO: There are 1201 '.bin' files in the folder.
-------------time_all: 3.124552, time_seg: 1.725843
label_file path is: /home/kilox/code/dataset_4090/SemanticKITTI/ScribbleKITTI/data_odometry_voxels_all/sequences/10/voxels/000000.label

XXXXXXXXXXXXXXXXXXXXXXX---LENGTH ERROR: 1048576 != 16384---XXXXXXXXXXXXXXXXXXXXXXXX

[dipgseg_node-3] process has died [pid 28634, exit code 1, cmd /home/kilox/code/code/detect/offline_function/video_detect_function/catkin_ws/devel/lib/dipgseg/offline_kitti_node 10 __name:=dipgseg_node __log:=/home/kilox/.ros/log/f875ab82-eda8-11ee-b1e3-244bfe056dd7/dipgseg_node-3.log].
log file: /home/kilox/.ros/log/f875ab82-eda8-11ee-b1e3-244bfe056dd7/dipgseg_node-3*.log
^C[rviz-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
(base) kilox@xsq:~/code/code/detect/offline_function/video_detect_function/catkin_ws$ roslaunch dipgseg visualization_offline_kitti.launch 
`
![飞书20240329-165737](https://github.com/EEPT-LAB/DipG-Seg/assets/27340686/62b0cc62-27d2-4c1b-ab21-143ba25e216c)

**Comment by wenhao12111** [comment]
> hello, when i run the visualization_offline_kitti.launch, there is en error of length, the log is such as the follow, an the rviz is nothing visualize.
> 
> `(base) kilox@xsq:~/code/code/detect/offline_function/video_detect_function/catkin_ws$ roslaunch dipgseg visualization_offline_kitti.launch ... logging to /home/kilox/.ros/log/f875ab82-eda8-11ee-b1e3-244bfe056dd7/roslaunch-xsq-28590.log Checking log directory for disk usage. This may take a while. Press Ctrl-C to interrupt Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://xsq:42355/
> 
> # SUMMARY
> PARAMETERS
> 
> * /dataset_path: /home/kilox/code/...
> * /eval_flag: False
> * /output_path: /home/kilox/code/...
> * /rosdistro: melodic
> * /rosversion: 1.14.13
> * /verbose: True
> 
> NODES / dipgseg_node (dipgseg/offline_kitti_node) rviz (rviz/rviz)
> 
> auto-starting new master process[master]: started with pid [28604] ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to f875ab82-eda8-11ee-b1e3-244bfe056dd7 process[rosout-1]: started with pid [28617] started core service [/rosout] process[rviz-2]: started with pid [28626] process[dipgseg_node-3]: started with pid [28634] now time is----------*********: 2024-03-29-16-47-28 INFO: Getting file paths from folder: /home/kilox/code/dataset_4090/SemanticKITTI/ScribbleKITTI/data_odometry_voxels_all/sequences/10/voxels INFO: There are 1201 '.bin' files in the folder. -------------time_all: 3.124552, time_seg: 1.725843 label_file path is: /home/kilox/code/dataset_4090/SemanticKITTI/ScribbleKITTI/data_odometry_voxels_all/sequences/10/voxels/000000.label
> 
> XXXXXXXXXXXXXXXXXXXXXXX---LENGTH ERROR: 1048576 != 16384---XXXXXXXXXXXXXXXXXXXXXXXX
> 
> [dipgseg_node-3] process has died [pid 28634, exit code 1, cmd /home/kilox/code/code/detect/offline_function/video_detect_function/catkin_ws/devel/lib/dipgseg/offline_kitti_node 10 __name:=dipgseg_node __log:=/home/kilox/.ros/log/f875ab82-eda8-11ee-b1e3-244bfe056dd7/dipgseg_node-3.log]. log file: /home/kilox/.ros/log/f875ab82-eda8-11ee-b1e3-244bfe056dd7/dipgseg_node-3*.log ^C[rviz-2] killing on exit [rosout-1] killing on exit [master] killing on exit shutting down processing monitor... ... shutting down processing monitor complete done (base) kilox@xsq:~/code/code/detect/offline_function/video_detect_function/catkin_ws$ roslaunch dipgseg visualization_offline_kitti.launch ` ![飞书20240329-165737](https://private-user-images.githubusercontent.com/27340686/318004142-62b0cc62-27d2-4c1b-ab21-143ba25e216c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDY3NzMsIm5iZiI6MTcxMTcwNjQ3MywicGF0aCI6Ii8yNzM0MDY4Ni8zMTgwMDQxNDItNjJiMGNjNjItMjdkMi00YzFiLWFiMjEtMTQzYmEyNWUyMTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDEwMDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZDM1YTNjMWNiMDJhNGEwZWNiNTUxOTcxOGNhNzkzNGY1NDBlMGU2Njk1ZjlmYmNkOTBhMmVjMDNhZmUxNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AzR2GA2FS5uhAhwpoKjHh-7UClO_CkAKIHcoAcziKMw)

Your dataset path is not right. You direct it to the 'voxels'.

**Comment by wenhao12111** [comment]
due to no further reply, the issue is closed.
