### ISSUE TITLE
projection_param 宏定义问题

### ISSUE THREAD

**Issue by niuwengang** [EEPT-LAB/DipG-Seg#9]
https://github.com/EEPT-LAB/DipG-Seg/blob/main/src/include/projection_param.h
该头宏定义的写法可能存在问题
原代码 在 #define  NUSCENES 时无法起到应有作用，建议修改为：
```
#if defined KITTI  
//
#elif defined(KITTI_LITE)
//
#elif defined(NUSCENES)
//
#elif defined(YOURLIDAR_CONFIG)
//
#endif
```
https://github.com/niuwengang/EvolvingAD/blob/6420c84d3622688522e73e1a4bf6acb1f89abe8e/src/evolving_ad/thirdpartylib/dipg_seg/include/projection_param.h#L1-L2

**Comment by wenhao12111** [comment]
> https://github.com/EEPT-LAB/DipG-Seg/blob/main/src/include/projection_param.h
> 该头宏定义的写法可能存在问题
> 原代码 在 #define  NUSCENES 时无法起到应有作用，建议修改为：
> ```
> #if defined KITTI  
> //
> #elif defined(KITTI_LITE)
> //
> #elif defined(NUSCENES)
> //
> #elif defined(YOURLIDAR_CONFIG)
> //
> #endif
> ```
> https://github.com/niuwengang/EvolvingAD/blob/6420c84d3622688522e73e1a4bf6acb1f89abe8e/src/evolving_ad/thirdpartylib/dipg_seg/include/projection_param.h#L1-L2
> 
> 

感谢您对工作的支持，我们当时测试时未注意到这个问题，如果您通过更改后能实现目标效果，那是最好啦～～～😁
